SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*) AS CNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') >= 9 AND DATE_FORMAT(DATETIME, '%H') < 20
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY HOUR